config/routes.rb
Omalley::Application.routes.draw do
  resources :testimonials

  get "pages/home"

  get "pages/george_o_malley"

  get "pages/contact"

  get "pages/about"

  resources :project_types

  resources :photos

  resources :projects

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match "*path" => redirect("/")

root :to => 'projects#index'

end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id            :integer          not null, primary key
#  image_url     :string(255)
#  project_id    :integer
#  caption       :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  running_order :integer
#

class Photo < ActiveRecord::Base
  attr_accessible :caption, :image_url, :project_id, :running_order

  # associations
  belongs_to :project

  # validation
  validates :project_id, presence: true
  validates :image_url, presence: true

  # callbacks
  #before_destroy :check_for_dependencies

  # scopes
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json

  before_filter :get_variables

  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
  private

  def get_variables
    @projects = Project.all
  end
  # def get_variables
  #   @photos = Photo.all
  # end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.collection_select :project_id, @projects, :id, :name, prompt: 'Select..' %>
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :running_order %><br />
    <%= f.text_field :running_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Image url</th>
    <th>Project</th>
    <th>Caption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.image_url %></td>
    <td><%= photo.project_id %></td>
    <td><%= photo.caption %></td>
    <td><%= photo.running_order %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image url:</b>
  <%= @photo.image_url %>
</p>

<p>
  <b>Project:</b>
  <%= @photo.project_id %>
</p>

<p>
  <b>Caption:</b>
  <%= @photo.caption %>
</p>

<!--<p>-->
  <!--<b>Running Order:</b>-->

<!--</p>-->


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>