config/routes.rb
Omalley::Application.routes.draw do
  resources :testimonials

  get "pages/home"

  get "pages/george_o_malley"

  get "pages/contact"

  get "pages/about"

  resources :project_types

  resources :photos

  resources :projects

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match "*path" => redirect("/")

root :to => 'projects#index'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :description, :email, :name, :company, :title
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  # GET /testimonials
  # GET /testimonials.json

  before_filter :get_variables

  def index
    @testimonials = Testimonial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testimonials }
    end
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/new
  # GET /testimonials/new.json
  def new
    @testimonial = Testimonial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/1/edit
  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render json: @testimonial, status: :created, location: @testimonial }
      else
        format.html { render action: "new" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      if @testimonial.update_attributes(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy

    respond_to do |format|
      format.html { redirect_to testimonials_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def testimonial_params
      params.require(:testimonial).permit(:description, :email, :name, :company, :title)
    end

  def get_variables
    @testimonials = Testimonial.all
    @projects = Project.all

  end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<div class="container marketing">
  <!--<h2 class="well">Testimonials</h2>-->


<!--  <%= link_to 'New Testimonial', new_testimonial_path %>-->




  <% @testimonials.each do |testimonial| %>
    <% if testimonial.email != "none" %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-titles" style = text-shadow:none><%= testimonial.try(:name)%></h4>
          <h5 class="panel-titles" style = text-shadow:none><%= testimonial.try(:company)%> - <%= testimonial.try(:title)%> - <%= link_to testimonial.try(:email), testimonial.try(:email) %></h5>
        </div>
        <div class="panel-body" style = text-shadow:none ><%= testimonial.try(:description) %>
           <%= link_to 'Edit', edit_testimonial_path(testimonial) %>
          <%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>

     <% end %>
  <% end %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-titles" style = text-shadow:none>Private Clients</h4>
    </div>
    <% @testimonials.each do |testimonial| %>
     <% if testimonial.email == "none" %>
    <div class="panel-body" style = text-shadow:none ><%= testimonial.try(:description) %>
        <!--            <%= link_to 'Edit', edit_testimonial_path(testimonial) %>
          <%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %>-->

    </div>
      <% end %>
    <% end %>
  </div>






</div>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @testimonial.name %>
</p>


<p>
  <b>Company:</b>
  <%= @testimonial.company %>
</p>

<p>
  <b>Title:</b>
  <%= @testimonial.title %>
</p>

<p>
  <b>Description:</b>
  <%= @testimonial.description %>
</p>

<p>
  <b>Website:</b>
  <%= @testimonial.email %>
</p>


<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>