config/routes.rb
Omalley::Application.routes.draw do
  resources :testimonials

  get "pages/home"

  get "pages/george_o_malley"

  get "pages/contact"

  get "pages/about"

  resources :project_types

  resources :photos

  resources :projects

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  match "*path" => redirect("/")

root :to => 'projects#index'

end

app/views/layouts/_flash_notices.html.erb
<div>
  <% if flash[:notice] %>
    <div class="span12 alert alert-block alert-info">
      <button type="button" class="close" data-dismiss="notice">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="span12 alert alert-block alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wrapper" style="margin-bottom: 0">
  <div  class="container">

    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Omalley</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!--DBD commented out line above to try use gem instead 26.2.15 %%%% THEN %%% undid this on 2.3.15-->

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>

  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <script type="text/javascript"src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
  <script src="script.js"></script>
  <![endif]-->
  <style>
    .carousel-inner > .item {
      -webkit-transition: 2.0s ease-in-out left;
      -moz-transition: 2.0s ease-in-out left;
      -o-transition: 2.0s ease-in-out left;
      transition: 2.0s ease-in-out left;
    }
  </style>
</head>
<body>

<div class = "navbar navbar-inverse navbar-static-top">

  <div class = "container">

    <a href = "#" class = "navbar-brand">O'Malley Plastering</a>
      <button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
        <span class = "icon-bar"></span>
        <span class = "icon-bar"></span>
        <span class = "icon-bar"></span>

      </button>
      <div class = "collapse navbar-collapse navHeaderCollapse">

        <ul class = "nav navbar-nav navbar-right">


          <li><%= link_to 'Home', projects_url %></li>
          <li><%= link_to 'About', pages_about_path %></li>
          <li><%= link_to 'Projects', projects_url %></li>
          <li><%= link_to "George O'Malley", pages_george_o_malley_path %></li>
          <li><%= link_to 'Testimonials', testimonials_url %></li>
          <li><%= link_to 'Contact', contact_url %></li>

        </ul>
      </div>
  </div>
</div>
<%= render partial: '/layouts/flash_notices' %>


  <%= yield(:full_width_stuff) %>
  <div class="container ">
    <%= yield %>

  </div>
  <div class="row col-sm-2">
  </div>
    <div class="row col-sm-8">

    </div>
  <div class="row col-sm-2">
  </div>


  <footer class="footer" style ="background-color: #1b1b1b;, padding: 5px;">
    <div class="container">
      <div class="row text-muted">
        <div class="col-sm-6">
          <div class="row">
            <div class="col-sm-6">
              <h5>Phone +353 1 2116706</h5>
              <h5>Phone +353 1 2116708</h5>
              <h5>Fax   +353 1 2022708</h5>
              <h5>Email</h5> <h5> <a href="mailto:info@omalleyplastering.com"> info@omalleyplastering.com</a></h5>
            </div>
            <div class="col-sm-6">
              <h5> Unit 3</h5>
              <h5> Ballywaltrim Business Park</h5>
              <h5> Boghall Road</h5>
              <h5> Bray</h5>
              <h5> Co. Wicklow</h5>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <% this_testimonial = Testimonial.find(Testimonial.pluck(:id).sample)  %>
              <h4> What people say about O'Malley Plastering </h4>             <!--h5 s are blocks-->
              <strong><em><%= this_testimonial.name  %>:</em></strong>
              <%= truncate(this_testimonial.description, length: 235)  %>
              <strong><em><%= link_to 'more', testimonials_url %></em></strong>
            </div>
          </div>
          <h4> Accreditations  and Memberships </h4>
          <%= link_to image_tag('/assets/ISO 9001.gif', alt: "National Standards Authority of Ireland Logo"), "http://www.nsai.ie/Our-Services/Certification/Management-Systems/ISO-9001.aspx" %>
          <%= link_to image_tag('/assets/IQnet.gif', alt: "IQNET Logo"),   "http://www.iqnet-certification.com/" %>
          <%= link_to image_tag('/assets/igs.jpeg', alt: "Irish Georgian Society Logo" ), "http://www.igs.ie/conservation/register" %>
          <%= link_to image_tag('/assets/heritage_contractor.jpeg', alt: "Heritage Contractor Logo" ), "http://www.heritageregistration.ie/what-is-a-heritage-contractor/" %>
        </div>



        <div class="col-sm-6 text-center">
          <a class="twitter-timeline" href="https://twitter.com/DeirdreBloomer" data-widget-id="581054433385144320">Tweets by @DeirdreBloomer</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

          <div class="row" >
            <br/>
            <button class="btn text-center" type="button" > We are in the process of updating our website.....   check back soon.   </button>
            </div>
        </div>
      </div>
    </div>
  </footer>


</body>

</html>